# This file is submitted by GPC_Submit.pbs
# Only the function calls you want to run should be uncommented.
# This file contains all of the function calls I've used. 
#   It's an easy way to go back and rerun things or saw what I ran before.

setwd('~/Research/GPC/GPC_Codes')
source('./GPC_Main.R')

# qsub <- function() {system('qsub /sscc/home/c/cbe117/Research/GPC/GPC_Codes/GPC_Submit.pbs')}
# pbstat <- function() {system('pbstat')}

#RGPTest3()
#QuickTest2()
#RGPTest4() # All fits
#RGPTest5() # All in 2D again
#RGPTest6() # All in 1D again
#SSCCTest1()
#SSCCTest2()
#SSCCTest3()
#SSCCRun001(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun001()
#SSCCRun001(only.compare=T)
#SSCCRun002(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun002()
#SSCCRun002(only.compare=T)
#SSCCRun003(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun003(only.compare=T)
#SSCCRun003()
#SSCCRun004(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun004(only.compare=T)
#SSCCRun004()
#SSCCRun005(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun005(only.compare=T)
#SSCCRun005()
#SSCCRun006(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun006(only.compare=T)
#SSCCRun006()
#SSCCRun007(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun007(only.compare=T)
#SSCCRun008(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun008(only.compare=T)
#SSCCRun009(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun009(only.compare=T)
#SSCCRun010(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun010(only.compare=T)
#SSCCRun011(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun011(only.compare=T)
#SSCCRun012(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#SSCCRun012(only.compare=T)
#SSCCRun013()
#SSCCRun014()
#SSCCRun015()
#SSCCRun016()
#SSCCRun017()
#SSCCRun018()
#SSCCRun013(only.compare=T)
#SSCCRun014(only.compare=T)
#SSCCRun015(only.compare=T)
#SSCCRun016(only.compare=T)
#SSCCRun017(only.compare=T)
#SSCCRun018(only.compare=T)
#SSCCRun019()
#SSCCRun020()
#SSCCRun021()
#SSCCRun022()
#SSCCRun019(only.compare=T)
#SSCCRun020(only.compare=T)
#SSCCRun021(only.compare=T)
#SSCCRun022(only.compare=T)

#Borehole01(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#Borehole01(only.compare=T)
#Borehole01(GPfit.include=F,mlegp.include=F,laGP.include=F,Python.include=F,GPy.include=T,DACE.include=F)
#Borehole01(only.compare=T,GPfit.controls=1)
#Borehole01_1()
#Borehole01_2()
#Borehole01_3()
#Borehole02(GPfit.include=T,mlegp.include=F,laGP.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#Borehole02(GPfit.include=F,only.compare=T)
#Borehole02(GPfit.include=F,only.compare=T)
#Borehole02(GPfit.include=F,laGP.include=F,mlegp.include=T,GPy.include=F,Python.include=F,DACE.include=F,laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#Borehole02(GPfit.include=T,only.compare=T, laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6))
#Borehole1357_02(GPfit.include=T,laGP.include=F,mlegp.include=F,GPy.include=F,Python.include=F,DACE.include=F)
#Borehole1357(GPfit.include=T,laGP.include=F,mlegp.include=F,GPy.include=F,Python.include=F,DACE.include=F)
#Borehole1357(GPfit.include=F,laGP.include=F,mlegp.include=F,GPy.include=T,Python.include=F,DACE.include=F)
#Borehole1357_02(GPfit.include=F,laGP.include=F,mlegp.include=T,GPy.include=F,Python.include=F,DACE.include=F,laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#Borehole1357_02(only.compare=T,laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6))

#SSCCRun023()
#SSCCRun024()
#SSCCRun025()
#SSCCRun026()
#SSCCRun023(only.compare=T)
#SSCCRun024(only.compare=T)
#SSCCRun025(only.compare=T)
#SSCCRun026(only.compare=T)
#SSCCRunRU01()
#SSCCRunRU02()
#SSCCRunRU03()

#RGPP_D1_B0()
#RGPP_D2_B0()
#RGPP_D3_B0()
#RGPP_D4_B0()
#RGPP_D5_B0()
#RGPP_D6_B0()
#RGPP_D1_B0(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D2_B0(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D3_B0(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D4_B0(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D5_B0(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B0(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D1_B0(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D2_B0(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D3_B0(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D4_B0(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D5_B0(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D6_B0(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)

#RGPP_D1_B1()
#RGPP_D2_B1()
#RGPP_D3_B1()
#RGPP_D4_B1()
#RGPP_D5_B1()
#RGPP_D6_B1()
#RGPP_D1_B1(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D2_B1(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D3_B1(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D4_B1(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D5_B1(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B1(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D1_B1(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D2_B1(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D3_B1(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D4_B1(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D5_B1(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D6_B1(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)

#RGPP_D1_B2()
#RGPP_D2_B2()
#RGPP_D3_B2()
#RGPP_D4_B2()
#RGPP_D5_B2()
#RGPP_D6_B2()
#RGPP_D1_B2(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D2_B2(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D3_B2(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D4_B2(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D5_B2(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B2(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D1_B2(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D2_B2(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D3_B2(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D4_B2(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D5_B2(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D6_B2(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)

#RGPP_D6_B000111()
#RGPP_D6_B000222()
#RGPP_D6_B111222()
#RGPP_D6_B001122()
#GPP_D6_B000111(mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B000222(mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B111222(mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B001122(mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B000111(only.compare=T)
#RGPP_D6_B000222(only.compare=T)
#RGPP_D6_B111222(only.compare=T)
#RGPP_D6_B001122(only.compare=T)

#OTLCircuit1()
#OTLCircuit1(mlegp.include=F,laGP.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#OTLCircuit1(GPfit.include=F)
#OTLCircuit1(GPfit.include=F,mlegp.include=F,laGP.include=F,Python.include=F,GPy.include=T,DACE.include=F)
#OTLCircuit1(only.compare=T,mlegp.include=F)
#OTLCircuit1(GPfit.include=F,laGP.include=F,mlegp.include=T,GPy.include=F,Python.include=F,DACE.include=F,laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#OTLCircuit1(only.compare=T, mlegp.include=F, laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6))


#Braninsc1()

#Detpep108d1(GPfit.include=F,GPfit.controls=1) # No GPfit
#Detpep108d1(GPfit.include=T,GPfit.controls=1,GPfit.powers=2,laGP.include=F,GPy.include=F,Python.include=F,mlegp.include=F,DACE.include=F)
#Detpep108d1(GPfit.include=T,GPfit.controls=1,GPfit.powers=1.95,laGP.include=F,GPy.include=F,Python.include=F,mlegp.include=F,DACE.include=F)
#Detpep108d1(GPfit.include=F,laGP.include=T,GPy.include=F,Python.include=F,mlegp.include=F,DACE.include=F) # Only GPy
#Detpep108d1(only.compare=T,GPfit.controls=1,mlegp.include=F) # OC
#Detpep108d1(GPfit.include=F,laGP.include=F,mlegp.include=T,GPy.include=F,Python.include=F,DACE.include=F,laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#Detpep108d1(only.compare=T, mlegp.include=T, laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6))

#Franke2D1()
#Fried1()

#RGPP_D1_B.7(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D2_B.7(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D3_B.7(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D4_B.7(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D5_B.7(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D6_B.7(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D1_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D2_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D3_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D4_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D5_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D6_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F)
#RGPP_D1_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D2_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D3_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D4_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D5_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=F)
#RGPP_D6_B.7(only.compare=F,GPfit.powers=c(2),GPfit.controls=1,   laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D1_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=T,DACE.include=F,laGP.include=F)
#RGPP_D2_B.7(GPfit.include=F,mlegp.include=T,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=F, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D3_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=T,DACE.include=F,laGP.include=F)
#RGPP_D4_B.7(GPfit.include=F,mlegp.include=T,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=F, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D5_B.7(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=T,DACE.include=F,laGP.include=F)
#RGPP_D6_B.7(GPfit.include=F,mlegp.include=T,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=F, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D1_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=T)
#RGPP_D2_B.7(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D2_B.7(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),reps.run=1:5)
#RGPP_D3_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=T)
#RGPP_D4_B.7(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),reps.run=1:5)
#RGPP_D5_B.7(only.compare=T,GPfit.powers=c(2),GPfit.controls=1,GPy.include=T)
#RGPP_D6_B.7(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6))

#RGPP_D1_B1.3(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D2_B1.3(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D3_B1.3(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D4_B1.3(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D5_B1.3(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D6_B1.3(GPfit.powers=c(2),GPfit.controls=1)
#RGPP_D1_B1.3(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=T, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D2_B1.3(GPfit.include=F,mlegp.include=T,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=F, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D3_B1.3(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=T, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D4_B1.3(GPfit.include=F,mlegp.include=T,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=F, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D5_B1.3(GPfit.include=F,mlegp.include=F,Python.include=F,GPy.include=F,DACE.include=F,laGP.include=T, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D6_B1.3(GPfit.include=T,mlegp.include=T,Python.include=T,GPy.include=T,DACE.include=T,laGP.include=T, laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D1_B1.3(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3),mlegp.include=F)
#RGPP_D2_B1.3(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),reps.run=1:5)
#RGPP_D3_B1.3(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D4_B1.3(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),reps.run=1:5)
#RGPP_D5_B1.3(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3))
#RGPP_D6_B1.3(only.compare=T,GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6))


# Running things with JMP now
#RGPP_D1_B1.3(stepstorun=3,GPfit.powers=c(2), laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3),mlegp.include=F,JMP.include=T,external.fits='JMP')
#Borehole1357_02(stepstorun=3,laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#Borehole02(stepstorun=3,laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#OTLCircuit1(stepstorun=3, laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#Detpep108d1(stepstorun=3, laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#RGPP_D2_B.7(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP',reps.run=1:5)
#RGPP_D4_B.7(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP',reps.run=1:5)
#RGPP_D6_B.7(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#RGPP_D2_B1.3(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP',reps.run=1:5)
#RGPP_D4_B1.3(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP',reps.run=1:5)
#RGPP_D6_B1.3(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')


# Redoing everything, including JMP separately
#RGPP_D1_B1.3(stepstorun=3,GPfit.powers=c(2), laGP.nuggets=c('E',1e-8,1e-6,1e-3),laGP.nuggets.names=c('E',8,6,3),mlegp.include=F,JMP.include=T,external.fits='JMP')
#Borehole1357_03(stepstorun=3,laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#Borehole03(stepstorun=3,laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#OTLCircuit2(stepstorun=3, laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
Detpep108d2(stepstorun=1:3, laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP', GPfit.include=F, GPy.include=F)
#RGPP2_D2_B.7( stepstorun=1:3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=F,external.fits='JMP', GPfit.include=T, mlegp.include=T, GPy.include=T)
#RGPP2_D4_B.7( stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#RGPP2_D6_B.7( stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#RGPP2_D2_B1.3(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#RGPP2_D4_B1.3(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
#RGPP2_D6_B1.3(stepstorun=3, GPfit.powers=c(2), laGP.nuggets=c('E',1e-6),laGP.nuggets.names=c('E',6),JMP.include=T,external.fits='JMP')
