
---
title: "Report"
output: html_document
---


# Input

Input | Value
------------------- | ----------------
Function |  No funcString given
Input dimension |  6
Design sample size |  200
Prediction sample size |  2000

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//OTLCircuit2//OTLCircuit2_D6_SS200_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```
