
---
title: "Report"
output: html_document
---


# Input

Input | Value
------------------- | ----------------
Function |  RGP.points 2 50 2000 0.7 2 1028
Input dimension |  2
Design sample size |  50
Prediction sample size |  2000

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_by_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_on_PRMSE_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_outlier.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_on_PRMSE_over_LM_stripchart_log.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_on_PRMSE_over_QM_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RMSE_scatter.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//R2_stripchart.png")
grid.raster(img)
  ```

```{r fig.width=10, fig.height=10,echo=FALSE}
library(png)
library(grid)
img <- readPNG("//sscc//home//c//cbe117//Research//GPC//GPC_Output//RGPP2_D2_B.7//RGPP2_D2_B.7_D2_SS50_PS2000_R5//Plots//RunTimes.png")
grid.raster(img)
  ```
